# Generated by Django 5.0.3 on 2024-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensetype_suggestiontype_expenses_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
