# Generated by Django 5.0.3 on 2024-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_suggestions_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestiontype',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
